version: '3.8'

services:
  # Serviço da API Spring Boot
  api:
    build: .  # Usa o Dockerfile da pasta
    container_name: spring-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod  # ⬅️ Usará application-prod.properties
      #POSTGRESSQL
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/seletivo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_DRIVER=org.postgresql.Driver

      #MINIO
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      
      #JPA/HIBERNATE
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect

      #Segurança
      - JWT_PRIVATE_KEY=classpath:app.key
      - JWT_PUBLIC_KEY=classpath:app.pub
      - JWT_TOKEN_EXPIRATION_MINUTES=5
      #CORS
      - URL_FRONTEND=http://localhost:4200

    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    networks:
      - minha-rede

  # Serviço do PostgreSQL
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      - POSTGRES_DB=seletivo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - minha-rede
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Serviço do MinIO
  minio:
    image: quay.io/minio/minio
    container_name: minio-storage
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"  # API MinIO
      - "9001:9001"  # Console MinIO
    networks:
      - minha-rede

# Volumes para persistência
volumes:
  postgres-data:
  minio-data:

# Rede para comunicação entre containers
networks:
  minha-rede:
    driver: bridge
